config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path=> '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :products do
    resources :comments
  end
    
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  resources :orders, only: [:index, :show, :create, :destroy]

  root 'static_pages#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
    if user.admin? 
    	can :manage, :all
    else
    	can :manage, [User, Product], id: user.id
    end
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: :true
  	validates :user, presence: :true
  	validates :product, presence: :true
  	validates :rating, numericality: { only_integer: true}

  belongs_to :user
  belongs_to :product

  scope :rating_desc, -> { order(rating: :desc) }
  scope :rating_asc, -> { order(rating: :asc) }

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: :true

	has_many :orders
	has_many :comments

	def higest_rating_comment
		comments.rating_desc.first
	end

	def lowest_rating_comment
		comments.rating_asc.first
	end

	def average_rating
		comments.average(:rating).to_f
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to main_app.root_url, :alert => exception.message
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@product = Product.find(params[:product_id])
		@comment = @product.comments.new(comment_params)
		@comment.user = current_user
		@user = current_user
		respond_to do |format|
			if @comment.save
				format.html { redirect_to @product, notice: 'Review was created successfully.' }
				format.json { render :show, status: :created, location: @product }
			else
				format.html { redirect_to @product, alert: 'Review was not saved successfully.'}
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end	
	end

	def destroy
		@comment = Comment.find(params[:id])
		product = @comment.product
		@comment.destroy
		redirect_to product
	end

	private

		def comment_params
			params.require(:comment).permit(:user_id, :body, :rating)
		end	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_filter :authenticate_user!

	def index
	end

	def show
	end

	def new
	end

	def create
	end

	def destroy
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.production?
        @products = Product.where("name ilike ?", "%#{search_term}%")
      else
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      end
    else
      @products = Product.all
    end 
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.'}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
  	@products = Product.limit(3)
  end

  def thank_you
  	@name = params[:name]
  	@email = params[:email]
  	@message = params[:message]
  	ActionMailer::Base.mail(:from => @email,
  		:to => 'daniellefamble@gmail.com',
  		:subject => "A new contact form message from #{@name}",
  		:body => @message).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Nameofapp</title>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button><!-- END BUTTON -->
					<%= link_to("Bike Berlin", root_path, "class" => 'navbar-brand') %>
				</div><!-- END NAVBAR-HEADER -->
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<li>
								<%= form_tag("/products", method: "get", class: "navbar-form") do %>
									<%= label_tag(:q, "Search for:") %>
									<%= text_field_tag(:q) %>
									<%= submit_tag("Search", class: "btn btn-default") %>
								<% end %>
							</li>
							<li>
								<%= link_to("Shop", products_path, class: "nav-text") %>
							</li>
							<li>
								<%= link_to("About", static_pages_about_path, class: "nav-text") %>
							</li>
							<li>
								<%= link_to("Contact", static_pages_contact_path, class: "nav-text") %>
							</li>
							<li>
							<% if user_signed_in? %>
								<%= link_to('Sign out', destroy_user_session_path, :method=> :delete, class: "btn btn-info login") %>
							<% else %>
								<%= link_to('Login', new_user_session_path, class: "btn btn-info login") %>
							<% end %>			
							</li>
						</ul><!-- END UL NAV -->
					</div><!-- END NAVBAR-COLLAPSE -->
			</div><!-- END CONTAINER-FLUID -->
		</nav><!-- END NAV -->
		<% if notice %>
			<p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
		<% end %>
		<% if alert %>
  		<p id="notice" class="alert alert-info" role="alert"><%= alert %></p>
  	<% end %>	
		
		<%= yield %>

		<footer class="footer">
			<div class="container-fluid">
				<p class="footer-content">
					&copy; 2016 Bike Berlin
				</p><!-- END FOOTER CONTENT -->
			</div><!-- END FOOTER DIV -->
		</footer><!-- END FOOTER -->
	</body>
</html>

app/views/products/_comments.html.erb
<div class="product-reviews col-xs-12">
	<% @comments.each do |comment| %>
		<div class="row">
			<hr>
			<p>
				<%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
				<% if signed_in? && current_user.admin? %>
					<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>	
			</p>
			<p><%= "Rating: #{comment.rating}/5" %></p>
			<div class="rated" data-score="<%= comment.rating %>"></div>
			<p><%= comment.body %></p>
		</div>
	<% end %>
	<br>
	<%= will_paginate@comments %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
    <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
	<h4>Add a review:</h4>
	<%= form_for([@product, @product.comments.build]) do |f| %>
		<p>
			<%= f.label :body, "Comments" %><br>
			<%= f.text_area :body, class: "form-control", rows: "5" %>
		</p>
		<p>
			<div class="rating"></div>
		</p>
		<p>
			<%= f.submit "Submit", class: "btn btn-primary" %>
		</p>
	<% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-12 col-md-4">
  <%= image_tag(product.image_url, class: 'img-responsive') %>
  <h2><%= product.name %></h2>
  <p><%= product.description %></p>
  <p><%= product.color %></p>
  <p><strong><%= product.price %></strong></p>
  <td><%= link_to 'Show', product, class: "btn btn-default" %></td>
  <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-default" %></td>
  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
</div><!-- END COL -->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">Our Bikes</h1>

<div class="container-fluid">
  <div class="row">
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>
  </div><!-- END ROW -->
</div><!-- END CONTAINER-FLUID -->

<br>

<%= link_to 'Add New Product', new_product_path, class: "btn btn-default" %>
  

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <%= image_tag(@product.image_url, class: "img-responsive", id: "product-img") %>
    </div>
    <div class="col-xs-6 col-md-4">
      <h2><%= @product.name %></h2>
      <h4><%= @product.price %></h4>
      <p>
        <strong>Color:</strong>
        <%= @product.color %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>
      <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></p>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row col-xs-12">
    <p>
      <strong>Customer Reviews:</strong><hr>
      <strong>Top Positive Review:</strong><%= @product.higest_rating_comment %><br>
      <strong>Top Critical Review:</strong><%= @product.lowest_rating_comment %>
    </p>
    <div>
      <%= render partial:'new_comment' %>
    </div>
    <div>
      <%= render partial:'comments' %>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<body class="about-page">
	<div class="container-fluid">
		<div id="about-article" class="col-xs-12 col-md-6">
			<h1>About Us</h1>
			<hr>
			<p>We are a full service bicycle shop located in the heart of Berlin. We believe the best way to see the city is on your own set of wheels. Bike Berlin offers affordable, used bikes for tourists and locals alike.</p><br>

			<p>Scott and Brad Cohen, brothers from San Francisco, opened Bike Berlin in 2012. They visited Berlin during the summer of their senior year of college. The brothers rented bicycles to explore the city and loved the experience so much they decided to stay. </p><br>

			<p>We hope to see you at Bike Berlin soon!</p>
		</div><!-- END ARTICLE -->
	</div><!-- END CONTAINER -->
</body>

app/views/static_pages/contact.html.erb
<body class="contact-page">
	<div class="container-fluid">
		<%= image_tag("Bicycle.png", class: "img-responsive my-image", id: "brand-image") %>
	</div>
	<div class="container-fluid col-xs-12 col-md-8 contact_left">
	<%= flash[:notice] %>
	<%= form_tag("/static_pages/thank_you") do %>
		<div class="form-group">
			<%= label_tag :name %>
			<%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
		</div>
		<div class="form-group">
			<%= label_tag :email, "Email Address" %>
			<%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
		</div>
		<div class="form-group">
			<%= label_tag :message %>
			<%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
		</div>	
		<%= submit_tag "Send", class: "btn btn-success" %>
	<% end %>
	</div><!-- END CONTACT LEFT -->

	<div class="container-fluid col-xs-12 col-md-4 contact_right">
		<h3>Contact Us</h3>
		<p>We can't wait to hear from you!</p>
		<ul class="list-unstyled">
			<li>
				<span class="glyphicon glyphicon-map-marker"></span>
				<span>Reiler Str. 72, 16235 Berlin, Germany</span>
			</li>
			<li>
				<span class="glyphicon glyphicon-envelope"></span>
				<span><%= mail_to("hallo@bikeberlin.de", "hallo@bikeberlin.de") %></span>
			</li>
			<li>
				<span class="glyphicon glyphicon-earphone"></span>
				<span><a href="tel:+49 111 1111111">+49 111 1111111</span>
			</li>
		</ul>
	</div><!-- END CONTACT RIGHT -->
</body>

app/views/static_pages/index.html.erb
<!-- <h1 class="welcome-headline">Welcome to Bike Berlin</h1> -->
<!-- <h2>Your source for used bikes in Berlin</h2> -->

<div class="container-fluid">
	<%= video_tag(['man-on-bike.mp4'], :id => "video-background", :autoplay => true, :loop => true, :muted => true, :type => "video/mp4") %>
	<div class="container-fluid">
		<div class="row text-center main-text">
			<h1>Bike Berlin</h1><br>
			<p><em>Explore Berlin on two wheels</em>
			</p><br>
			<div class="text-center">
				<%= link_to "Shop Now", products_path, class: "btn btn-success shop-now" %>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/landing_page.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
      <div class="item<%= " active" if product == @products.first %>">
        <%= image_tag(product.image_url) %>
        <div class="carousel-caption">
          <%= product.name %>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
	<div class="panel-body">
	<p>Thank you. We have recieved your message and will respond as soon as possible.</p>
	</div><!-- END PANEL BODY -->
</div><!-- END PANEL -->

<%= link_to("Back to the homepage", root_path) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>